### ISSUE TITLE
不能安裝

### ISSUE THREAD

**Issue by jaxon0523** [wildskyf/ihatecontentfarm#4]
我把xpi包拆開來發現裡面少了install.rdf檔
我想是不是這個緣故所以我的fx不能安裝
因為裡面有安裝擴充元件的描述檔的關係

但如果是WebExtension的話我就不知道需不需要install.rdf了…orz

```
名稱 	Firefox
版本 	50.1.0
Build ID 	20161210195403
更新記錄 	
使用者代理字串（User Agent） 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0
作業系統 	Windows_NT 10.0
```

**Comment by wildskyf** [comment]
@J4X0N 想問一下，你的 Firefox 是從 http://moztw.org 下載的官版 Firefox 嗎？

**Comment by jaxon0523** [comment]
@wildskyf 後來的可以了～謝謝！我是jaxon0523 XD

**Comment by wildskyf** [comment]
@J4X0M 原來就是你XD 可以就好！
